### ISSUE TITLE
MemoryError in join-git-repos.py

### ISSUE THREAD

**Issue by rustyx** [mbitsnbites/git-tools#3]
I'm getting this error shortly after join-git-repos.py starts:

```
Exporting the main repository (my.git)...
Traceback (most recent call last):
  File "C:\Projects\git-tools\join-git-repos.py", line 463, in <module>
    main_commands = exportrepo(main_spec['path'])
  File "C:\Projects\git-tools\join-git-repos.py", line 102, in exportrepo
    return parseexport(subprocess.check_output(cmd))
  File "C:\Python27\lib\subprocess.py", line 567, in check_output
    output, unused_err = process.communicate()
  File "C:\Python27\lib\subprocess.py", line 791, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "C:\Python27\lib\subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
MemoryError
fatal: Could not write blob 'f8c32f916652446202463db916551abc5513e78f': Broken pipe
```

**Comment by mbitsnbites** [comment]
Is the repo big? This could be a problem with out-of-memory. The design of join-git-repos is very simple in that it reads the entire git repo into RAM. I have not tried the tool with a very large repo (only ~1GB or so).

**Comment by eberlid** [comment]
For your information about RAM usage on large repos: we are joining about
30 repositories which ends up in a ~25 G repo. We do this on a Linux
machine with 25 G RAM and 150 G swap. The repos have a history of about 12
years and also contain binaries. Be prepared to spend some RAM/swap.

mbitsnbites <notifications@github.com> schrieb am Mo., 10. Juli 2017, 22:02:

**Comment by mbitsnbites** [comment]
@eberlid That's a grand project. Could you please report if things work out or not?

**Comment by eberlid** [comment]
It works! It uses lots of RAM as mentioned above, but that's something we
can scale.

I forked the project and implemented that notes are merged too. I don't
think it has the quality for a pull request, but we can work on that.

mbitsnbites <notifications@github.com> schrieb am Mi., 12. Juli 2017, 07:22:

**Comment by rustyx** [comment]
I'm trying to merge 3 repos, ~1GB each. The Windows 10 machine has 64GB of RAM, but still the third repo won't merge. Also tried with Python 2.7.13 from Cygwin x64, the python process grows to ~30GB then dumps with another error at the "Importing result" stage:

```
      0 [main] python2.7 13284 fhandler_dev_zero::fixup_mmap_after_fork: requested 0x6D026960000 != 0x0 mem alloc base 0x0, state 0x10000, size 133203467108352, Win32 error 1455
    197 [main] python2.7 13284 C:\cygwin64\bin\python2.7.exe: *** fatal error in forked process - recreate_mmaps_after_fork_failed
   1598 [main] python2.7 13284 cygwin_exception::open_stackdumpfile: Dumping stack trace to python2.7.exe.stackdump
      0 [main] python 9652 fork: child -1 - forked process 13284 died unexpectedly, retry 0, exit code 0x100, errno 11
Traceback (most recent call last):
  File "/c/Projects/git-tools/join-git-repos.py", line 492, in <module>
    importtorepo(out_root, main_commands, main_spec['branch'])
  File "/c/Projects/git-tools/join-git-repos.py", line 111, in importtorepo
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
OSError: [Errno 11] Resource temporarily unavailable
```
Granted, my third repo has quite some blobs that were added and deleted over the course of 18 years, but I don't think they add up to 133TB, maybe a couple of dozen GB max.

**Comment by eberlid** [comment]
I observed that the memory usage grows in the last few seconds of the
process. In our case it grows from about 120 G to 160 G.

I remember that we also got these errors when python tried to create a new
process (thread?). Basically you will have various stack traces depending
on which memory allocation call failed due to out of memory condition.
Creating a process requires memory.

In case you switch to a Linux machine: I also played around with overcommit
ratio and set it to 90 (I'm not a Linux power user, so probably this would
not be necessary... However, it worked).

Can you log available memory during joining?

Rustam Abdullaev <notifications@github.com> schrieb am Mi., 12. Juli 2017,
22:27:

**Comment by rustyx** [comment]
I'm going to close this issue as huge memory consumption is apparently by design; I couldn't see anything wrong with the Python script itself except that the whole repo history is exploded and appended to one giant string. So in theory it should work, provided enough virtual memory is available. As to my own repos, I'm keeping them separate for now.

**Comment by mbitsnbites** [comment]
It is by design. It solved my particular problem, so I did not bother tp make a more elavorate memory solution. If you want to support larger repos, one solution could be to keep all data blobs in temporary files instead, and parse/write the stdin/stdout in a blockwise manner.
